version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    env_file: ./docker/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: ./docker/pgadmin.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - private

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    env_file: ./docker/backend.env
    ports:
      - "3000:3000"
    depends_on:
      - pgadmin
    networks:
      - public
      - private
    hostname: backend

  frontend:
    build:
      context: ./front-end
      dockerfile: ../docker/frontend.dockerfile
    env_file: ./docker/frontend.env
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - public
    hostname: frontend

networks:
  public:
  private:

volumes:
  postgres_data:
  pgadmin_data: